# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 0 

    - name: Build Release
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
      run: |
        npm install
        npx quasar build

    - name: Git Version
      id: gitversion
      uses: codacy/git-version@2.5.4
      with:
        prefix: ${{ github.event.repository.name }}-v
        release-branch: main
        dev-branch: develop
        major-identifier: '/(?i)\brelease\b/'
      run: |
        echo ${{ steps.gitversion.outputs.version }}
        Compress-Archive dist/* ${{ steps.gitversion.outputs.version }}.zip

    - name: Upload New Release
      uses: xresloader/upload-to-github-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: "${{ steps.gitversion.outputs.version }}.zip"
        overwrite: true
        draft: false
        tag_name: ${{ steps.gitversion.outputs.version }}
