# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and Deploy on Release

on:
  release:
    types: [published]

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Git Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 0 

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: latest

    - name: Build Source
      run: |
        npm install
        npx quasar build
        
    - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

    - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/page:latest

    - name: Compress Build
      run: |
        sudo apt-get install zip
        cd dist/spa/
        zip -r ${{ github.event.release.tag_name }}.zip *

    - name: Upload Build zip to Release
      uses: xresloader/upload-to-github-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: "dist/spa/${{ github.event.release.tag_name }}.zip"
        overwrite: true
        draft: false
        tag_name: ${{ github.event.release.tag_name }}
